apiVersion: v1
kind: Service
metadata:
  name: event-journal-service
spec:
  type: ClusterIP
  selector:
    app: event-journal
    tier: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
